### ISSUE TITLE
Bug Report Extension issue and not loading tasks.

### ISSUE THREAD

**Issue by sheldonhull** [paulvarache/vscode-taskfile#18]
- Issue Type: `Bug`
- Extension Name: `vscode-taskfile`
- Extension Version: `0.0.5`
- OS Version: `Darwin x64 20.4.0`
- VS Code version: `1.56.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 29,
		"activateCallTime": 1,
		"activateResolvedTime": 1327,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "paulvarache.vscode-taskfile",
				"_lower": "paulvarache.vscode-taskfile"
			},
			"activationEvent": "workspaceContains:**/Taskfile.yml,**/Taskfile.yaml"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Connection got disposed."
		}
	]
}
```

**Comment by sheldonhull** [comment]
related #11 #12

Once I have more complex tasks it's failing with more detail here.

<details closed>
<summary>:bug: bug details (click to expand)</summary>

```log
jsonrpc] 2021/05/13 15:46:30 Found Handler for method extension/getTasks
[jsonrpc] 2021/05/13 15:46:30 Sending response: {"result":[],"error":null,"id":2}
[jsonrpc] 2021/05/13 15:49:08 Found Handler for method extension/getTasks
[jsonrpc] 2021/05/13 15:49:08 Sending response: {"result":[],"error":null,"id":3}
[jsonrpc] 2021/05/13 15:49:10 Found Handler for method textDocument/didChange
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method workspace/didChangeWatchedFiles
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1115cfc]

goroutine 36 [running]:
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x8, 0x113e4c0, 0x1, 0xc00016a4b0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:127 +0x28c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e9270, 0x11a6900, 0xc00015fb60, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x8, 0x113e4c0, 0x1, 0xc00016a4a8)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e9130, 0x11a6980, 0xc0002069f0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x8, 0x113e4c0, 0xc000159001, 0xc00016a498)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e8fa0, 0x11a6ac0, 0xc0002068d0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x11526a0, 0x1158400, 0xc00013e801, 0x11a6e00)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e8eb0, 0x11a6e00, 0xc000206870, 0x203001, 0x203000)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x8, 0x113e4c0, 0x1, 0xc00016a490)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:120 +0x237
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e8e10, 0x11a6940, 0xc0002066f0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x8, 0x113e4c0, 0x1, 0xc00016a478)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e8b40, 0x11a6940, 0xc0002064b0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x8, 0x113e4c0, 0x1, 0xc00016a460)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e8870, 0x11a6980, 0xc000206330, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x11526a0, 0x1158400, 0xc000158e01, 0x11a6e00)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e85f0, 0x11a6e00, 0xc0002061b0, 0x203001, 0x203000)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0001c3cc8, 0xc00016c600, 0x0, 0x0, 0x1, 0xc00015f780)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:120 +0x237
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0001c3cc8, 0xc00016c600, 0xc0001e8550, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parse(0xc0001c3cc8, 0xc0001ec000, 0xda, 0x100, 0x1, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:371 +0xf9
github.com/goccy/go-yaml/parser.Parse(0xc0001ec000, 0xda, 0x100, 0x1, 0x100, 0x14be, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:407 +0x57
github.com/goccy/go-yaml/parser.ParseBytes(0xc0001c7800, 0x14be, 0x16be, 0x1, 0xc00016a0f8, 0xc000116090, 0xc0001562e8)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:397 +0x9a
taskfile-language-server/taskfile.PreloadWithBytes(0xc00014a447, 0x33, 0xc0001c7800, 0x14be, 0x16be, 0x0)
	/Users/runner/runners/2.164.8/work/1/s/taskfile/taskfile.go:88 +0x4c
taskfile-language-server/taskfile.Preload(0xc00014a447, 0x33, 0xc00014a447, 0x33, 0x0)
	/Users/runner/runners/2.164.8/work/1/s/taskfile/taskfile.go:109 +0x7d
taskfile-language-server/extension.(*TaskfileExtension).WorkspaceDidChangeWatchedFiles(0xc000062290, 0xc00015e4a0)
	/Users/runner/runners/2.164.8/work/1/s/extension/workspace.go:20 +0x11c
taskfile-language-server/lsp.(*LSPServer).DidChangeWatchedFiles(0xc0000864b0, 0xc00001e720, 0x5b, 0x60)
	/Users/runner/runners/2.164.8/work/1/s/lsp/workspace.go:22 +0xcc
created by taskfile-language-server/jsonrpc.(*Server).GetResponse
	/Users/runner/runners/2.164.8/work/1/s/jsonrpc/jsonrpc.go:110 +0x2ea
[Info  - 3:49:11 PM] Connection to server got closed. Server will restart.
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method initialize
[jsonrpc] 2021/05/13 15:49:11 Sending response: {"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":1},"completionProvider":{"resolveProvider":true}}},"error":null,"id":0}
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method initialized
[jsonrpc] 2021/05/13 15:49:11 Sending response: {"result":null,"error":null,"id":0}
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method textDocument/didOpen
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method textDocument/didOpen
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method extension/getTasks
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1115cfc]

goroutine 11 [running]:
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x8, 0x113e4c0, 0x1, 0xc0001783b8)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:127 +0x28c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019f1d0, 0x11a6900, 0xc00015f5a0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x8, 0x113e4c0, 0x1, 0xc0001783b0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019f090, 0x11a6980, 0xc0001ba480, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x8, 0x113e4c0, 0xc00015cb01, 0xc0001783a0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019ef00, 0x11a6ac0, 0xc0001ba360, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x11526a0, 0x1158400, 0xc00013c601, 0x11a6e00)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019ee10, 0x11a6e00, 0xc0001ba300, 0x203001, 0x203000)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x8, 0x113e4c0, 0x1, 0xc000178398)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:120 +0x237
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019ed70, 0x11a6940, 0xc0001ba180, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x8, 0x113e4c0, 0x1, 0xc000178380)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019eaa0, 0x11a6940, 0xc000171f20, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x8, 0x113e4c0, 0x1, 0xc000178368)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019e7d0, 0x11a6980, 0xc000171da0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x11526a0, 0x1158400, 0xc00015c901, 0x11a6e00)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:150 +0x60c
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019e550, 0x11a6e00, 0xc000171c20, 0x203001, 0x203000)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parseMappingValue(0xc0000fbc68, 0xc000170090, 0x0, 0x0, 0x1, 0xc00015f1c0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:120 +0x237
github.com/goccy/go-yaml/parser.(*parser).parseToken(0xc0000fbc68, 0xc000170090, 0xc00019e4b0, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:339 +0x3bd
github.com/goccy/go-yaml/parser.(*parser).parse(0xc0000fbc68, 0xc00018e800, 0xda, 0x100, 0x1, 0x0, 0x0, 0x0)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:371 +0xf9
github.com/goccy/go-yaml/parser.Parse(0xc00018e800, 0xda, 0x100, 0x1, 0x100, 0x14be, 0xc00016dce8)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:407 +0x57
github.com/goccy/go-yaml/parser.ParseBytes(0xc00017a000, 0x14be, 0x1500, 0x1, 0x1500, 0x1500, 0x14be)
	/Users/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.2.0/parser/parser.go:397 +0x9a
taskfile-language-server/taskfile.PreloadWithBytes(0xc00014e080, 0x33, 0xc00017a000, 0x14be, 0x1500, 0x1500)
	/Users/runner/runners/2.164.8/work/1/s/taskfile/taskfile.go:88 +0x4c
taskfile-language-server/taskfile.GetParsedTaskfile(0xc00014e080, 0x33, 0x40)
	/Users/runner/runners/2.164.8/work/1/s/taskfile/taskfile.go:128 +0xc0
taskfile-language-server/extension.(*TaskfileExtension).GetTasks(0xc000062290, 0xc00001c280, 0x40, 0x40, 0x0, 0x0, 0x2c)
	/Users/runner/runners/2.164.8/work/1/s/extension/task.go:37 +0xc8
taskfile-language-server/jsonrpc.(*Server).GetResponse(0xc0000702a0, 0xc0000a0410, 0x0, 0x0, 0x0, 0x0)
	/Users/runner/runners/2.164.8/work/1/s/jsonrpc/jsonrpc.go:114 +0x10c
taskfile-language-server/jsonrpc.(*Server).HandleRequest(0xc0000702a0, 0xc0000a0410)
	/Users/runner/runners/2.164.8/work/1/s/jsonrpc/jsonrpc.go:123 +0x39
created by taskfile-language-server/jsonrpc.(*Server).Listen
	/Users/runner/runners/2.164.8/work/1/s/jsonrpc/jsonrpc.go:160 +0x6c
[Info  - 3:49:11 PM] Connection to server got closed. Server will restart.
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method initialize
[jsonrpc] 2021/05/13 15:49:11 Sending response: {"result":{"capabilities":{"textDocumentSync":{"openClose":true,"change":1},"completionProvider":{"resolveProvider":true}}},"error":null,"id":0}
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method initialized
[jsonrpc] 2021/05/13 15:49:11 Sending response: {"result":null,"error":null,"id":0}
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method textDocument/didOpen
[jsonrpc] 2021/05/13 15:49:11 Found Handler for method textDocument/didOpen
```
</details>
